// BYOK 多服务商配置 REST for the mobile client (设置·模型配置).
//
// Replaces the retired single-key contract (`/v1/users/me/llm-key`) with an account
// LIST of OpenAI-compatible providers (`/v1/users/me/llm-providers`). Each provider is
// one endpoint+key+default model; the account carries cross-provider chat / background
// default pointers, and the deployment-level fields (billing_mode / platform_available /
// platform_model / free_tier_active) now ride on the list response top-level.
//
// Types are written mobile-locally (per cross-platform-frontend.mdc: each app builds its
// own types; contract-rest-types is regenerated by the desktop block) so this module stays
// self-contained and typechecks regardless of package regeneration timing. Shapes track
// apps/server/openapi.json (LlmProvidersResponse / LlmProviderView / …).
import { apiFetch } from "@/api/client";

/** Settings view of one BYOK provider — never the plaintext key. */
export interface LlmProviderView {
  id: string;
  label: string;
  base_url: string;
  default_model: string;
  /** Connectivity result: unchecked | active | error. */
  status: string;
  is_default_chat: boolean;
  is_default_background: boolean;
  masked_key?: string | null;
  message?: string | null;
  price_cache_hit?: string | null;
  price_cache_miss?: string | null;
  price_output?: string | null;
  supports_tools?: boolean | null;
  created_at?: string | null;
  updated_at?: string | null;
}

/** An account default pointer: which provider + which model. */
export interface LlmDefaultPointer {
  provider_id: string;
  model: string;
}

/** The full 设置·模型配置 state: provider list + account pointers + deployment caps. */
export interface LlmProvidersResponse {
  providers: LlmProviderView[];
  /** Deployment billing mode (byok | platform). */
  billing_mode: string;
  /** Whether platform models are available on this deployment. */
  platform_available: boolean;
  /** Operator platform model id when platform is available. */
  platform_model?: string | null;
  /** True when a keyless user runs on the free tier (no provider + platform creds). */
  free_tier_active: boolean;
  default_chat?: LlmDefaultPointer | null;
  default_background?: LlmDefaultPointer | null;
}

/** Add one provider (first provider auto-becomes the chat default). `api_key` required. */
export interface CreateLlmProviderInput {
  api_key: string;
  base_url?: string | null;
  default_model?: string | null;
  label?: string;
  price_cache_hit?: string | null;
  price_cache_miss?: string | null;
  price_output?: string | null;
}

/** Partial update — omit `api_key` to keep the stored ciphertext (edit endpoint/model). */
export interface UpdateLlmProviderInput {
  api_key?: string | null;
  base_url?: string | null;
  default_model?: string | null;
  label?: string | null;
  price_cache_hit?: string | null;
  price_cache_miss?: string | null;
  price_output?: string | null;
}

/** Set the account chat / background default pointers. Tri-state: omit a field to leave it
 *  unchanged; send `background: null` to clear it (background then follows chat). */
export interface SetLlmDefaultsInput {
  chat?: LlmDefaultPointer | null;
  background?: LlmDefaultPointer | null;
}

/** Same phrasing as desktop LoginPage — admin sessions cannot use product APIs. */
export const ADMIN_PRODUCT_FORBIDDEN_MESSAGE =
  "此账号为管理员账号，请使用管理后台登录";

async function errorMessage(res: Response, fallback: string): Promise<string> {
  try {
    const body = (await res.json()) as {
      error?: { code?: string; message?: string };
    };
    if (body.error?.code === "ADMIN_PRODUCT_FORBIDDEN") {
      return ADMIN_PRODUCT_FORBIDDEN_MESSAGE;
    }
    return body.error?.message ?? `${fallback} (${res.status})`;
  } catch {
    return `${fallback} (${res.status})`;
  }
}

async function readProviders(
  res: Response,
  fallback: string,
): Promise<LlmProvidersResponse> {
  if (!res.ok) throw new Error(await errorMessage(res, fallback));
  return (await res.json()) as LlmProvidersResponse;
}

async function readProvider(
  res: Response,
  fallback: string,
): Promise<LlmProviderView> {
  if (!res.ok) throw new Error(await errorMessage(res, fallback));
  return (await res.json()) as LlmProviderView;
}

/** List the account's providers + default pointers + deployment capabilities. */
export async function listLlmProviders(): Promise<LlmProvidersResponse> {
  return readProviders(
    await apiFetch("/v1/users/me/llm-providers"),
    "加载失败",
  );
}

/** Add one OpenAI-compatible provider (returns the created provider view). */
export async function createLlmProvider(
  input: CreateLlmProviderInput,
): Promise<LlmProviderView> {
  const res = await apiFetch("/v1/users/me/llm-providers", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  return readProvider(res, "保存失败");
}

/** Update one provider (endpoint / model / label / price; key optional to keep). */
export async function updateLlmProvider(
  id: string,
  input: UpdateLlmProviderInput,
): Promise<LlmProviderView> {
  const res = await apiFetch(`/v1/users/me/llm-providers/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  return readProvider(res, "保存失败");
}

/** Remove one provider (account pointers + conversation overrides fall back cleanly). */
export async function deleteLlmProvider(id: string): Promise<void> {
  const res = await apiFetch(`/v1/users/me/llm-providers/${id}`, {
    method: "DELETE",
  });
  if (!res.ok) throw new Error(await errorMessage(res, "删除失败"));
}

/** Probe one provider's endpoint and persist 'active' / 'error' + supports_tools. */
export async function testLlmProvider(id: string): Promise<LlmProviderView> {
  const res = await apiFetch(`/v1/users/me/llm-providers/${id}/test`, {
    method: "POST",
  });
  return readProvider(res, "测试失败");
}

/** Set the account chat / background default model pointers (returns the full state). */
export async function setLlmDefaults(
  input: SetLlmDefaultsInput,
): Promise<LlmProvidersResponse> {
  const res = await apiFetch("/v1/users/me/llm-providers/defaults", {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  return readProviders(res, "保存失败");
}
